### ISSUE TITLE
Connection timing out

### ISSUE THREAD

**Issue by burkesquires** [SciGraph/SciGraph#166]
Hello,

I was using SciGraph, or more precicesly py-SciGraph, to test out some commands last week without any issue. When I try it today I am getting a timeout. Please see below. Perhaps it is an issue with the ucsd.edu server

I cannto reach geoffrey.crbs.ucsd.edu through a browser but crbs.ucsd.edu I can.

Regards,

Burke

!py-SciGraph-master/run-scigr.py ann "the big ears and the hippocampus neurons"
http://geoffrey.crbs.ucsd.edu:9000/scigraph/annotations/entities.json
Traceback (most recent call last):
  File "/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 135, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 90, in create_connection
    raise err
  File "/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 80, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/anaconda/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/anaconda/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/anaconda/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/anaconda/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/anaconda/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 160, in connect
    conn = self._new_conn()
  File "/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 144, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x1033c7b38>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 271, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='geoffrey.crbs.ucsd.edu', port=9000): Max retries exceeded with url: /scigraph/annotations/entities.json?content=the+big+ears+and+the+hippocampus+neurons (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1033c7b38>: Failed to establish a new connection: [Errno 60] Operation timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "py-SciGraph-master/run-scigr.py", line 118, in <module>
    main()
  File "py-SciGraph-master/run-scigr.py", line 88, in main
    func(sg, args)
  File "py-SciGraph-master/run-scigr.py", line 113, in annotate
    spans = sg.annotate(t)
  File "/Users/squiresrb/Documents/BCBB/Clinical Genomics/Ontology Annotation - Monarch/py-SciGraph-master/scigraph/api/SciGraph.py", line 52, in annotate
    response = self.get_response("annotations/entities", None, "json", {'content':content})
  File "/Users/squiresrb/Documents/BCBB/Clinical Genomics/Ontology Annotation - Monarch/py-SciGraph-master/scigraph/api/SciGraph.py", line 62, in get_response
    r = requests.get(url, params=payload)
  File "/anaconda/lib/python3.4/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/anaconda/lib/python3.4/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/anaconda/lib/python3.4/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/anaconda/lib/python3.4/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/anaconda/lib/python3.4/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='geoffrey.crbs.ucsd.edu', port=9000): Max retries exceeded with url: /scigraph/annotations/entities.json?content=the+big+ears+and+the+hippocampus+neurons (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1033c7b38>: Failed to establish a new connection: [Errno 60] Operation timed out',))

**Comment by burkesquires** [comment]
The connection seems to be working again.

**Comment by cmungall** [comment]
Not sure what the downtime was, sorry about this. 

The Monarch SciGraph instance will be switching to new servers with more meaningful URLs early in January.

**Comment by burkesquires** [comment]
Hi Chris, Thanks for the reply. Glad to see you here. That is great to know that there will be new servers. This is a great tool. Keep up the great work!
