### ISSUE TITLE
inconsistent behavior between /dynamic/ and /cypher/execute

### ISSUE THREAD

**Issue by tgbugs** [SciGraph/SciGraph#287]
It is not possible to run a cypher query for a `dynamic` endpoint via the `/cypher/execute` endpoint. This makes query development exceedingly difficult. The exact reason is unknown, however the differences in the two functions linked below are the source of the problem.

https://github.com/SciGraph/SciGraph/blob/master/SciGraph-services/src/main/java/io/scigraph/services/resources/CypherUtilService.java#L102

https://github.com/SciGraph/SciGraph/blob/master/SciGraph-services/src/main/java/io/scigraph/services/jersey/dynamic/CypherInflector.java#L85

**Comment by dbrnz** [comment]
It turns out that server errors are not the result of query execution but rather due to differences in the way respective result sets are processed.

In the particular instance causing problems the query is:
```
MATCH path1 = (c:Class{iri: "http://uri.neuinfo.org/nif/nifstd/nlx_154731"})
      -[:apinatomy:annotates]->(soma:NamedIndividual)    // soma lyph
      -[:apinatomy:conveys]->(linkSoma)                  // link connecting soma to axon and dendrite
      -[:apinatomy:target|apinatomy:source]->(nodeRoot)  // axon or dendrite root
      -[:apinatomy:sourceOf|apinatomy:nextChainStartLevels|apinatomy:next*1..]->(link)  // sourceOf is first and only once
      -[:apinatomy:fasciculatesIn]->(layer_or_end)
      -[:apinatomy:cloneOf*0..1]->()
      -[:apinatomy:supertype*0..1]->()
      -[:apinatomy:external]->(external)
      WHERE soma.`https://apinatomy.org/uris/readable/generated` IS NULL
      WITH path1, nodeRoot, layer_or_end AS layer
      OPTIONAL MATCH path2 = (layer)  // if we were in a layer, get the containing lyph as well
      -[:apinatomy:layerIn]->(end_housing)
      -[:apinatomy:external]->(end_housing_external)
      WITH path1, path2, nodeRoot
      MATCH path3 = (nodeRoot)        // extract chain for axon vs dendrite
      -[:apinatomy:rootOf]->(chain)
      RETURN path1, path2, path3
```

As a dynamic query it runs just fine. However when run against `/cypher/execute`, a HTTP 500 error is returned and the server log shows:
```
ERROR [2021-03-05 08:00:14,685] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 84b04cf7fcdef6e0
! java.lang.ClassCastException: [I cannot be cast to [Ljava.lang.String;
! at io.scigraph.services.resources.CypherUtilService.resultSerializer(CypherUtilService.java:200)
! at io.scigraph.services.resources.CypherUtilService.nodeGeneration(CypherUtilService.java:214)
! at io.scigraph.services.resources.CypherUtilService.resultSerializer(CypherUtilService.java:170)
! at io.scigraph.services.resources.CypherUtilService.execute(CypherUtilService.java:124)
```

Modifying `CypherUtilService.execute()` to include:
```
            for (Entry<String, Object> entry : row.entrySet()) {
              String key = entry.getKey();
              Object value = entry.getValue();
              logger.info("Result: " + key: '" + value.toString() + "'");
              resultSerializer(generator, key, value);
            }
```

finds key/value pairs:
```
Result: path2: (49342)-[https://apinatomy.org/uris/readable/layerIn,217907]->(50565)-[https://apinatomy.org/uris/readable/external,204644]->(9063)
Result: path1: (16)-[https://apinatomy.org/uris/readable/annotates,227666]->(49135)-[https://apinatomy.org/uris/readable/conveys,206749]->(51476)-[https://apinatomy.org/uris/readable/source,221818]->(52684)-[https://apinatomy.org/uris/readable/sourceOf,220812]->(50125)-[https://apinatomy.org/uris/readable/fasciculatesIn,222628]->(49342)-[https://apinatomy.org/uris/readable/cloneOf,203371]->(49001)-[https://apinatomy.org/uris/readable/supertype,202270]->(50678)-[https://apinatomy.org/uris/readable/external,208652]->(8999)
Result: path3: (52684)-[https://apinatomy.org/uris/readable/rootOf,225599]->(51228)
Result: path2: (49342)-[https://apinatomy.org/uris/readable/layerIn,217907]->(50565)-[https://apinatomy.org/uris/readable/external,204644]->(9063)
Result: path1: (16)-[https://apinatomy.org/uris/readable/annotates,227666]->(49135)-[https://apinatomy.org/uris/readable/conveys,206749]->(51476)-[https://apinatomy.org/uris/readable/target,209487]->(50016)-[https://apinatomy.org/uris/readable/sourceOf,213065]->(50011)-[https://apinatomy.org/uris/readable/fasciculatesIn,218963]->(49342)-[https://apinatomy.org/uris/readable/cloneOf,203371]->(49001)-[https://apinatomy.org/uris/readable/supertype,202270]->(50678)-[https://apinatomy.org/uris/readable/external,208652]->(8999)
Result: path3: (50016)-[https://apinatomy.org/uris/readable/rootOf,199430]->(49705)
```
with the last pair being the one causing the exception.
 
For comparison, after executing a dynamic query, `CypherInflector` builds a graph of the result set:
```
      Graph graph = tgu.resultToGraph(result);
```

Is this sufficient information to resolve the issue?
